### PR TITLE
Add collapsible columns table option

### PR DESCRIPTION
**Pull request by chriskirkland**
Add an option for the existing Table object to automatically collapse (i.e. not display) any columns where all entries are zero.  This reduces the complexity of the logic necessary for clients with large and/or modal tables (for example, `bx cs logging-config-get` from the IBM Cloud Kubernetes Service CLI).

Because we're using the [functional option pattern](https://dave.cheney.net/2014/10/17/functional-options-for-friendly-apis), this doesn't break the existing API for the package; it's simply an addition.

### Sample file
```
package main

import (
	"github.com/IBM-Cloud/ibm-cloud-cli-sdk/bluemix/terminal"
	"os"
	"fmt"
)

func main() {
	var table terminal.Table
	fmt.Println("--- normal ---")
	table = terminal.NewTable(os.Stdout, []string{"name", "message", "comments"})
	table.Add("foo", "", "this works fine")
	table.Add("bar", "", "wrong indent")
	table.Add("bar", "", "still wrong indent")
	table.Print()
	fmt.Println()

	fmt.Println("--- collapsible ---")
	table = terminal.NewTable(os.Stdout, []string{"name", "message", "comments"}, terminal.WithCollapsibleColumns("message"))
	table.Add("foo", "", "this works fine")
	table.Add("bar", "", "wrong indent")
	table.Add("bar", "", "still wrong indent")
	table.Print()
	fmt.Println()
}
```

### Sample output
```
--- normal ---
name   message   comments
foo              this works fine
bar              wrong indent
bar              still wrong indent

--- collapsible ---
name   comments
foo    this works fine
bar    wrong indent
bar    still wrong indent
```

### CODE REVIEW

**Comment by boyang9527** [comment]
LGTM

**Comment by chriskirkland** [comment]
@weieigao have any more thoughts about this PR?

**Comment by chriskirkland** [comment]
@weieigao could you please take another look when you have a chance?  Last we left it, we discussed one alternative UX design, but you wanted some time to think about it.

**Comment by weieigao** [comment]
@chriskirkland , really sorry for the late response...
The idea of functional option is great, but:
1. As we've discussed before, the param in`func(Table)` is interface`Table` which only has `Add()` & `Print()`. How can the user use it to configure the terminal table? 
I saw type assertion is used here but don't think it's a good practise. Even the concrete type `PrintableTable` is not really accessible outside of the package (none of its attr is exported)
2. Is "collapsible column" really a **general** feature of a terminal table that should be implemented by SDK?  There 're other ways to support the feature, for example simply wrap the`Table`, remove collapsible columns before call its `Add()` & `Print()`

**Comment by chriskirkland** [comment]
@weieigao ok, I understand your difference of opinion.  

I can move it into our downstream project.  My big concern there is that we're going to have to copy a significant amount of the Table implementation from the SDK because the implementation I propose relies on direct access to the unexposed fields (e.g. `rows` and `headers`).

**Comment by weieigao** [comment]
@chriskirkland  what about something like this:

```
type CollapsibleTable struct {
	headers []string
	rows [][]string
	collapsibleColumns []int
}

func (t *CollapsibleTable) Print(w io.Writer) {
        // collapse headers/columns
	t.collapse()

        // initialize SDK's terminal table, and call Print()
   	table := ui.NewTerminalTable(w, t.headers)
	for _, r := range t.rows() {
		table.Add(r)
	}
	table.Print()
}
```

**Pull request closed without merging**
